SCREEN_WIDTH = 1024
SCREEN_HEIGHT = 768
DISPLAY = (SCREEN_WIDTH, SCREEN_HEIGHT)

PLATFORM_WIDTH = 20
PLATFORM_HEIGHT = 20
PLATFORM_AREA = (PLATFORM_WIDTH, PLATFORM_HEIGHT)
PLATFORM_COLOR = 0, 0, 0

GRAVITY = 0.35
JUMP_POWER = 10
